package com.pronovoscm.model;

public enum TransactionModuleEnum {
    ALBUM,
    PHOTO,
    CREW,
    WEATHER,
    PUNCHLIST,
    PUNCHLIST_ATTACHMENT,
    PUNCHLIST_HISTORY,
    PUNCHLIST_REJECT_REASON_ATTACHMENT,
    WORK_DETAIL,
    WORK_DETAIL_ATTACHMENT,
    DRAWING_ANNOTATION,
    WORK_IMPACT,
    WORK_IMPACT_ATTACHMENT,
    PROJECT_FORM_SUBMIT,
    FORM_IMAGE,
    PHOTO_DELETE,
    SYNC_OLD_FILES,
    ISSUE_TRACKING
}
